[package]
name = "SoOS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.26", default-features = false, features = ["alloc"] }
limine = "0.1.10"
once_cell = { version = "1.18.0", default-features = false }
x86_64 = { version = "0.14.10", default-features = false, features = ["abi_x86_interrupt"] }
