name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: install dependencies
              run: >
                  set -xeu &&
                  sudo apt install libisoburn1t64 &&
                  rustup toolchain install nightly &&
                  wget https://ziglang.org/download/0.14.1/zig-x86_64-linux-0.14.1.tar.xz &&
                  tar -xf *.tar.xz &&
                  ln -s zig-*/zig /usr/local/bin/zig

            - name: make
              run: make build/SoOS.iso
